[info]
# Nostr Nsec
nostr_nsec = "<>"
# Default mint
mint = "https://8333.space:3338"
# Default relays to publish and read from
relays=["wss://relay.damus.io", "wss://nostr.oxtr.dev"]
# Optional Invoice Description
# invoice_description=""